Makefile: use "-C utf8" argument for texindy
The error was:
Loading module "tex/inputenc/latin.xdy"...

Error in line 4:
;; Generated from latin?.xdy

Binary
ERROR: EVAL: variable BINARY has no value

Same error as described in "latin.xdy is built incorrectly (causing crash)"
https://bugs.launchpad.net/ubuntu/+source/xindy/+bug/1735439